spring.application.name=contasdacasa-app
# Configuracao do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/contasdacasa
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuracao do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Flyway gerencia o schema (ADR-0004)
spring.flyway.enabled=true
